from cspy import Crystal
import numpy as np
from cspy.db import CspDataStore
from cspy.util.path import TemporaryDirectory
import logging
import subprocess
import os
from cspy.util.misc import group_close_numbers
from typing import Dict, List, Tuple

LOG = logging.getLogger(__name__)


def get_potential_gapped_structures(dbname: str) -> Dict[str, Crystal]:
    """
    Get structures that are likely to have gaps in their 3D structure.

    Parameters:
        dbname (str): The name of the database to query.

    Returns:
        dict: A dictionary of structure IDs and Crystal objects that are likely to have gaps.
    """
    ds = CspDataStore(dbname)
    max_density = ds.query(
        "SELECT MAX(density) FROM crystal WHERE density IS NOT NULL"
    ).fetchone()[0]
    LOG.info("Maximum density in the database: %s", max_density)
    LOG.info(
        "Using 0.5 * max_density = %s as the cutoff density for potential gapped structures",
        0.5 * max_density,
    )

    potential_gapped_structures = ds.query(
        "SELECT id, file_content FROM crystal WHERE density IS NOT NULL AND density < ?",
        (0.5 * max_density,),
    ).fetchall()
    ds.close()

    if not potential_gapped_structures:
        LOG.info(f"No structure with density < {0.5*max_density} found in the database.")
        return {}

    # Calculating cutoff for one structure
    _, file_content = potential_gapped_structures[0]
    crystal = Crystal.from_shelx_string(file_content)
    cutoff = crystal.get_repulsion_dispersion_cutoff()
    LOG.info(
        "Using cutoff of %s angstrom for getting potential gapped structures", cutoff
    )

    picked_structures = {}
    for structure_id, file_content in potential_gapped_structures:
        crystal = Crystal.from_shelx_string(file_content)
        standard_crys = crystal.standardized()
        if standard_crys is not None:
            crystal = standard_crys
        else:
            LOG.warning(
                "Structure %s could not be standardized, using original structure.",
                structure_id,
            )
        if np.any(np.array(crystal.unit_cell.lengths) > cutoff):
            LOG.debug(
                "Structure %s has unit cell lengths larger than cutoff: %s",
                structure_id,
                crystal.unit_cell.lengths,
            )
            picked_structures[structure_id] = crystal
    return picked_structures


def is_slab_by_zeopp(crystal: Crystal, probe_diameter: float = None) -> bool:
    """
    Check if a crystal structure has gaps larger than the specified cutoff.
    Zeo++ is used to determine the 2D channels in the structure.

    Parameters:
        crystal (Crystal): The crystal structure to check.
        probe_diameter (float, optional): The probe diameter distance in Angstrom. Default is None,
            which means the diameter will be calculated automatically. Zeo++
            takes the probe radius, so in calculations this value will be halved.

    Returns:
        bool: True if the structure has gaps larger than the cutoff, False otherwise.
    """
    if probe_diameter is None:
        probe_diameter = crystal.get_repulsion_dispersion_cutoff()

    with TemporaryDirectory(prefix="zeo_", dir=".") as tmpdirname:
        LOG.debug("Created temp directory: %s", tmpdirname)
        input_cif_path = os.path.join(tmpdirname, "input.cif")
        with open(input_cif_path, "w") as f:
            f.write(crystal.to_cif_string())

        try:
            result = subprocess.run(
                ["network", "-chan", str(probe_diameter / 2), "input.cif"],
                cwd=tmpdirname,
                capture_output=True,
                text=True,
                check=True,
            )
            LOG.debug("Network command output: %s", result.stdout)
        except subprocess.CalledProcessError as e:
            LOG.error("Error running network command: %s", e.stderr)
            return False

        chan_file_path = os.path.join(tmpdirname, "input.chan")
        if not os.path.exists(chan_file_path):
            LOG.error("Channel file not generated by Zeo++.")
            return False

        with open(chan_file_path, "r") as f:
            line1 = f.readline().strip()
            parts = line1.split()
            if int(parts[1]) > 0:  # parts[1] is the number of channels found
                for dimension in parts[6:]:  # parts[6:] are the dimensions of the channels
                    if float(dimension) >= 2:
                        LOG.debug("Gaps found in structure: %s", parts)
                        return True
    return False


def get_gapped_structures(dbname: str, ncores: int = 1) -> List[str]:
    """
    Get structures that are likely to have gaps in their 3D structure using
    pre-screening density and lattice dimension measures and Zeo++ to confirm
    gapped structures.

    Parameters:
        dbname (str): The name of the database to query.
        ncores (int): Number of cores to use for parallel processing. Default is 1.

    Returns:
        List[str]: A list of structure IDs that are likely to have gaps.
    """
    from concurrent.futures import ThreadPoolExecutor
    from tqdm import tqdm

    potential_gapped_structures = get_potential_gapped_structures(dbname)

    def check_gapped(item: Tuple[str, Crystal]) -> str | None:
        structure_id, crystal = item
        probe_diameter = crystal.get_repulsion_dispersion_cutoff() / 2
        # Check if the structure is a slab
        if crystal.is_slab(tolerance=probe_diameter):
            LOG.info(
                "Structure %s is a slab with gaps > %s. Verifying with Zeo++...",
                structure_id,
                probe_diameter,
            )
        else:
            return None
        if is_slab_by_zeopp(crystal, probe_diameter=probe_diameter):
            LOG.info("Structure %s is detected as gapped by Zeo++", structure_id)
            return structure_id
        else:
            LOG.info("Structure %s is not gapped by Zeo++", structure_id)
            return None

    gapped_ids = []
    items = list(potential_gapped_structures.items())
    with ThreadPoolExecutor(max_workers=ncores) as executor:
        results = executor.map(check_gapped, items)
        for structure_id in tqdm(
            results, total=len(items), desc="Processing potential structures by Zeo++"
        ):
            if structure_id is not None:
                gapped_ids.append(structure_id)
    return gapped_ids


def create_table_if_not_exists(dbname: str, table_name: str) -> None:
    """
    Create a table in the database if it does not already exist.

    Parameters:
        dbname (str): The name of the database to update.
        table_name (str): The name of the table to create.
    """
    LOG.info(
        "Creating table %s in database %s if it does not exist",
        table_name,
        dbname,
    )
    ds = CspDataStore(dbname)
    ds.query(
        f"""
        CREATE TABLE IF NOT EXISTS {table_name} (
            id TEXT PRIMARY KEY,
            spacegroup INTEGER,
            density REAL,
            energy REAL,
            molecule_id TEXT,
            file_content TEXT
        )
        """
    )
    ds.close()


def move_structures_to_a_different_table(
    dbname: str, ids: List[str], table_name: str
) -> None:
    """
    Move structures from the crystal table to a different table in the database.

    Parameters:
        dbname (str): The name of the database to update.
        ids (List[str]): A list of structure IDs that are gapped.
        table_name (str): The name of the target table to move structures to.
    """
    create_table_if_not_exists(dbname, table_name)
    ds = CspDataStore(dbname)

    for structure_id in ids:
        row = ds.query(
            """
            SELECT id, spacegroup, density, energy, molecule_id, file_content
            FROM crystal WHERE id = ?
            """,
            (structure_id,),
        ).fetchone()
        if row:
            ds.query(
                f"""
                INSERT OR REPLACE INTO {table_name} 
                (id, spacegroup, density, energy, molecule_id, file_content) 
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                row,
            )
            ds.query("DELETE FROM descriptor WHERE id = ?", (structure_id,))
            ds.query(
                """
                DELETE FROM equivalent_to 
                WHERE ? IN (unique_id, equivalent_id)
                """,
                (structure_id,),
            )
            ds.query("DELETE FROM trial_structure WHERE id = ?", (structure_id,))
            ds.query("DELETE FROM crystal WHERE id = ?", (structure_id,))
        else:
            LOG.warning("Structure ID %s not found in crystal table", structure_id)
    ds.close()


def remove_gapped_structures(
    dbname: str, ncores: int = 1
) -> None:
    """
    Remove gapped structures from the crystal table and move them to gapped_crystal table.

    Parameters:
        dbname (str): The name of the database to update.
        ncores (int): Number of cores to use for parallel processing. Default is 1.
    """
    create_table_if_not_exists(
        dbname=dbname,
        table_name="gapped_crystal"
    )
    LOG.info("Gathering gapped structures from the database %s", dbname)
    gapped_structures = get_gapped_structures(dbname, ncores=ncores)
    LOG.info(
        "Removing %d gapped structures from the database %s",
        len(gapped_structures),
        dbname,
    )
    if not gapped_structures:
        LOG.info("No gapped structures found.")
        return

    move_structures_to_a_different_table(
        dbname, ids=gapped_structures, table_name="gapped_crystal"
    )
    LOG.info(
        "%d Gapped structures moved to gapped_crystal table.",
        len(gapped_structures),
    )


def get_lower_energy_thresholds_for_removing_structures(
    dbname: str, grouping_threshold: float = 10.0
) -> float:
    """
    Get lower energy thresholds for removing structures from the database.

    Parameters:
        dbname (str): The name of the database to query.
        grouping_threshold (float): The maximum difference between energies to be grouped together.
                                    Default is 10.

    Returns:
        float: The energy thresholds below which structures will be counted as Buckingham
               catastrophies and removed.
    """
    ds = CspDataStore(dbname)
    energies = ds.query(
        "SELECT energy FROM crystal WHERE energy IS NOT NULL"
    ).fetchall()
    ds.close()

    if not energies:
        raise ValueError("No energy data found in the database.")

    energies = [e[0] for e in energies]
    grouped_energies = group_close_numbers(energies, threshold=grouping_threshold)

    # IDEA:
    # Find the largest group of energies which hopefully represents the main body of landscape.
    # Then set the threshold to min(energy) - 0.5*(range of distribution of energies).
    # Considering that the max(energy)=0, threshold equals 1.5*min(largest_group).
    largest_group = max(grouped_energies, key=lambda group: len(group))
    min_energy_in_largest_group = min(largest_group) if largest_group else None
    if min_energy_in_largest_group is None or min_energy_in_largest_group >= 0:
        return None
    return 1.5 * min_energy_in_largest_group


def get_buckingham_catastrophies(
    dbname: str,
    grouping_threshold: float = 10,
    manual_energy_threshold: float = None,
) -> List[str]:
    """
    Get Buckingham catastrophies from the database.

    Parameters:
        dbname (str): The name of the database to query.
        grouping_threshold (float): The maximum difference between energies to be grouped together.
                                    Default is 10.
        manual_energy_threshold (float): If provided, use this value as the energy threshold instead of
                                         calculating it automatically. Default is None.

    Returns:
        List[str]: A list of structure IDs that are considered Buckingham catastrophies.
    """
    if manual_energy_threshold is not None:
        LOG.info("Using manual energy threshold: %s", manual_energy_threshold)
        threshold = manual_energy_threshold
    else:
        LOG.info("Calculating energy threshold for removing structures.")
        # Automatically calculate the energy threshold based on the database content
        threshold = get_lower_energy_thresholds_for_removing_structures(
            dbname, grouping_threshold
        )
        LOG.info("Energy threshold for removing structures: %s", threshold)

    if threshold is None:
        LOG.info("No energy data found in the database.")
        return []

    ds = CspDataStore(dbname)
    ids_to_remove = ds.query(
        "SELECT id FROM crystal WHERE energy IS NOT NULL AND energy < ?",
        (threshold,),
    ).fetchall()
    ds.close()

    return [row[0] for row in ids_to_remove]


def remove_buckingham_catastrophies(
    dbname: str,
    grouping_threshold: float = 10,
    energy_threshold: float = None,
) -> None:
    """
    Remove Buckingham catastrophies from the database.

    Parameters:
        dbname (str): The name of the database to update.
        grouping_threshold (float): The maximum difference between energies to be grouped together.
                                    Default is 10.
        energy_threshold (float): If provided, use this value as the energy threshold for removing
                                  Buckingham catastrophies. Default is None, which means the threshold
                                  will be calculated automatically.
    """
    create_table_if_not_exists(
        dbname=dbname,
        table_name="buckingham_catastrophies"
    )
    LOG.info("Gathering Buckingham catastrophies from the database %s", dbname)
    ids_to_remove = get_buckingham_catastrophies(
        dbname,
        grouping_threshold=grouping_threshold,
        manual_energy_threshold=energy_threshold,
    )
    LOG.info(
        "Removing %d Buckingham catastrophies from the database %s",
        len(ids_to_remove),
        dbname,
    )
    if not ids_to_remove:
        LOG.info("No Buckingham catastrophies found.")
        return

    move_structures_to_a_different_table(
        dbname, ids=ids_to_remove, table_name="buckingham_catastrophies"
    )
    LOG.info(
        "%d Buckingham catastrophies moved to buckingham_catastrophies table.",
        len(ids_to_remove),
    )


def write_outlier_structures_to_res_files(
    dbname: str,
    output_prefix: str = "output",
) -> None:
    """
    Write outlier structures (gapped structures and Buckingham catastrophies) to res files.
    Files will be named <output_prefix>_gapped_crystal.res and <output_prefix>_buckingham_catastrophies.res.

    Parameters:
        dbname (str): The name of the database to query.
        output_prefix (str): Prefix for the output res file. Default is "output".
    """
    ds = CspDataStore(dbname)
    for table in ("gapped_crystal", "buckingham_catastrophies"):
        file_contents = ds.query(
            f"SELECT file_content FROM {table}"
        ).fetchall()
        if file_contents:
            output_file = f"{output_prefix}_{table}.res"
            with open(output_file, "w") as file:
                for (content,) in file_contents:
                    if content:
                        crystal = Crystal.from_shelx_string(content)
                        standard_crystal = crystal.standardized() or crystal
                        file.write(standard_crystal.to_shelx_string())
                        file.write("\nEND\n")
            LOG.info(
                "Standardized %s written to %s",
                table.replace("_", " "),
                output_file,
            )
    ds.close()


def main(sys_args=None) -> None:
    import argparse
    from cspy.util.logging_config import FORMATS, DATEFMT
    import shutil

    if shutil.which("network") is None:
        LOG.error(
            "Zeo++ 'network' executable not found in PATH. "
            "Please install Zeo++ and ensure 'network' is available."
        )
        exit(1)

    parser = argparse.ArgumentParser(
        description=(
            "Remove gapped structures and undetected Buckingham catastrophies from the database. "
            "Gapped structures are identified using Zeo++ and are moved to gapped_crystal table. "
            "Buckingham catastrophies are identified based on an automatically detected/manually "
            "provided energy threshold and are moved to buckingham_catastrophies table."
        )
    )
    parser.add_argument(
        "dbnames",
        type=str,
        nargs="+",
        help="The name(s) of the database(s) to process.",
    )
    parser.add_argument(
        "--log-level",
        type=str,
        choices=("INFO", "DEBUG", "ERROR", "WARN"),
        default="INFO",
        help="Control level of logging output",
    )
    parser.add_argument(
        "--grouping-threshold",
        type=float,
        default=10.0,
        help=(
            "The maximum difference between energies to be grouped together. "
            "Default is 10.0."
        ),
    )
    parser.add_argument(
        "--energy-threshold",
        type=float,
        default=None,
        help=(
            "If provided, use this value as the energy threshold for removing Buckingham catastrophies. "
            "Default is None, which means the threshold will be calculated automatically."
        ),
    )
    parser.add_argument(
        "--write-res",
        action="store_true",
        help="Write the (standardized) outlier structures to a concatenated shelx file.",
    )
    parser.add_argument(
        "--output-resfile-prefix",
        type=str,
        default=None,
        help=(
            "Prefix for the output res file containing standardized outlier structures. "
            "Default is 'output'. The full filenames will be <prefix>_gapped_structures.res "
            "and <prefix>_buckingham_catastrophies.res."
        ),
    )
    parser.add_argument(
        "-n",
        "--ncores",
        type=int,
        default=1,
        help=(
            "Number of cores to use for parallel processing of Zeo++ calculations. "
            "Default is 1."
        ),
    )
    args = parser.parse_args(sys_args)
    logging.basicConfig(
        level=args.log_level, format=FORMATS[args.log_level], datefmt=DATEFMT
    )

    for dbname in args.dbnames:
        LOG.info("Starting outlier removal process for database %s", dbname)
        remove_gapped_structures(
            dbname,
            ncores=args.ncores,
        )
        LOG.info("Finished removing gapped structures from the database %s", dbname)
        remove_buckingham_catastrophies(
            dbname,
            grouping_threshold=args.grouping_threshold,
            energy_threshold=args.energy_threshold,
        )
        LOG.info(
            "Finished removing Buckingham catastrophies from the database %s", dbname
        )

        if args.write_res:
            write_outlier_structures_to_res_files(
                dbname,
                output_prefix=(
                    dbname.replace(".db", "")
                    if args.output_resfile_prefix is None
                    else args.output_resfile_prefix
                ),
            )


if __name__ == "__main__":
    main()
