from collections import defaultdict
from pathlib import Path
from typing import List, Tuple

import numpy as np

from cspy import Crystal
from cspy.crystal import AsymmetricUnit, UnitCell, SpaceGroup
from cspy.util.constants import BOHR2ANGSTROM
from cspy.util.path import Path


def to_fractional(coords: np.ndarray, lattice_vectors: np.ndarray) -> np.ndarray:
    """
    Convert direct/cartesian coords to fractional.

    Args:
        coords (np.ndarray): Cartesian coordinates of atoms.
        lattice_vectors (np.ndarray): Direct lattice vectors of the crystal structure.

    Returns:
        np.ndarray: Fractional coordinates of atoms.
    """
    inverse = np.linalg.inv(lattice_vectors)
    return np.dot(coords, inverse)


def to_direct(coords: np.ndarray, lattice_vectors: np.ndarray) -> np.ndarray:
    """
    Convert fractional coords to direct/cartesian.

    Args:
        coords (np.ndarray): Fractional coordinates of atoms.
        lattice_vectors (np.ndarray): Direct lattice vectors of the crystal structure.

    Returns:
        np.ndarray: Cartesian coordinates of atoms.
    """
    return np.dot(coords, lattice_vectors)


def read_energy_prediction(fname: str = "energy.comp") -> dict:
    """
    Parse energies from energy.comp generated by nnp-dataset.

    Args:
        fname (str): Path to the energy.comp file. Default is "energy.comp".

    Returns:
        dict: A dictionary containing the predicted energies for each system.
            The keys are the system indices, and the values are dictionaries with
            'ref' and 'nnp' keys for reference and NNP energies.
    """
    predicted_energy_dict = {}
    with open(fname, 'r') as f:
        for line in f.readlines():
            if line[0] == '#':
                continue
            parts = line.split()
            predicted_energy_dict[int(parts[0])] = {
                'ref': float(parts[2]),
                'nnp': float(parts[3])
            }
    return predicted_energy_dict


def read_forces_prediction(fname: str = "forces.comp") -> dict:
    """
    Parse forces from forces.comp generated by nnp-dataset.
    Requires 'use_short_forces' in the input.nn.

    Args:
        fname (str): Path to the forces.comp file. Default is "forces.comp".

    Returns:
        dict: Dict containing key for each system predicted. Value is a dict containing
            'ref' and 'nnp' keys for lists of forces predicted by each method in order of
            atoms in input.data then in order fx fy fz.
    """
    predicted_force_dict = {}
    with open(fname, 'r') as f:
        for line in f.readlines():
            if line[0] == '#':
                continue
            parts = line.split()
            idx = int(parts[0])
            if idx not in predicted_force_dict:
                predicted_force_dict[idx] = {
                    'ref': [],
                    'nnp': []
                }
            predicted_force_dict[idx]['ref'].append(float(parts[2]))
            predicted_force_dict[idx]['nnp'].append(float(parts[3]))
    return predicted_force_dict


def parse_n2p2_data_content(
    file_content: str
) -> List[Tuple[str, np.ndarray, List[dict], float, float]]:
    """
    Parse n2p2 input.data file content.

    Args:
        file_content (str): The contents of the file as a single continuous string.

    Returns:
        list: List of tuples containing:
            comment (str): The comment line.
            lattice_vectors (np.ndarray): The direct lattice vectors.
            atoms (List[dict]): Dict for each atom including label, element, position, forces.
            energy (float): Energy of system.
            charge (float): Charge of system.
    """
    structure_data = []
    entries = file_content.split('end')

    for entry in entries:
        contents = entry.split("\n")

        comment = None
        lattice_vectors = []
        atoms = []
        energy = None
        charge = None
        element_count = defaultdict(int)

        for line in contents:
            line_content = line.split()
            if len(line_content) < 1:
                continue

            if line_content[0] == 'comment' and len(line_content) > 1:
                comment = ' '.join(line_content[1:])
            elif line_content[0] == 'lattice':
                lattice_vectors.append(
                    [float(x) for x in line_content[1:]]
                )
            elif line_content[0] == 'atom':
                atom_coords = np.array([float(x) for x in line_content[1:4]])
                element = line_content[4]
                forces = [float(x) for x in line_content[7:]]
                element_count[element] += 1
                label = element + str(element_count[element])
                atoms.append(
                    {
                        'label': label,
                        'element': element,
                        'position': atom_coords,
                        'forces': forces,
                    }
                )
            elif line_content[0] == 'energy':
                energy = float(line_content[1])
            elif line_content[0] == 'charge':
                charge = float(line_content[1])
            else:
                continue
        if atoms:
            structure_data.append(
                (comment, np.array(lattice_vectors), atoms, energy, charge)
            )

    return structure_data


def from_n2p2_input_data_file(
    filepath: str = 'input.data', **kwargs
) -> List[Crystal]:
    """
    Initialize a crystal structure from a n2p2 .data file.

    Args:
        filepath (str): Path to the n2p2 input.data file. Default is 'input.data'.
        **kwargs: Additional keyword arguments to pass to the Crystal constructor.

    Returns:
        List[Crystal]: List of cspy Crystal objects corresponding to the structures in the n2p2 input.data file.
    """
    p = Path(filepath)
    return from_n2p2_input_data_str(p.read_text(), **kwargs)


def from_n2p2_input_data_str(
    file_content: str, atomic_units: bool = False, **kwargs
) -> List[Crystal]:
    """
    Initialize a crystal structure from a n2p2 .data string.

    Args:
        file_content (str): The content of the n2p2 input.data file as a string.
        atomic_units (bool): If True, the lengths are interpreted in atomic units (Bohr radius) rather than Angstrom. Default is False.
        **kwargs: Additional keyword arguments to pass to the Crystal constructor.

    Returns:
        List[Crystal]: List of cspy Crystal objects corresponding to the structures in the file.
    """
    crystals = []
    structure_data = parse_n2p2_data_content(file_content)

    for structure in structure_data:
        comment, lattice_vectors, atom_records, energy, charge = structure

        if atomic_units:
            lattice_vectors = lattice_vectors * BOHR2ANGSTROM
            for atom_data in atom_records:
                atom_data['position'] = atom_data['position'] * BOHR2ANGSTROM

        if len(lattice_vectors) < 1:
            raise NotImplementedError('the file is a molecule')

        # Convert to fractional (n2p2 input.data is direct coords, cspy is fractional)
        for atom_data in atom_records:
            atom_data['position'] = to_fractional(
                atom_data['position'],
                lattice_vectors
            )
        asymmetric_unit = AsymmetricUnit.from_records(atom_records)
        unit_cell = UnitCell(lattice_vectors)
        sg_int_table_num = kwargs.get('spacegroup', 1)

        crystal = Crystal(
            unit_cell,
            SpaceGroup(sg_int_table_num),
            asymmetric_unit,
            titl=kwargs.pop("titl", comment),
            **kwargs,
        )

        crystal.properties['energy'] = energy
        crystal.properties['atom_forces'] = np.array(
            [atom['forces'] for atom in atom_records]
        )

        crystals.append(crystal)

    return crystals


def to_n2p2_input_data_file(crys: Crystal, filename: str = "input.data") -> None:
    """
    Write cspy crystal to n2p2 input.data file.

    Args:
        crys (Crystal): cspy Crystal object to convert.
        filename (str): Name of the output file. Default is "input.data".

    Returns:
        None
    """
    with open(filename, 'w') as f:
        f.write(to_n2p2_input_data_str(crys))


def to_n2p2_input_data_str(crys: Crystal, **kwargs) -> str:
    """
    Convert cspy crystal to n2p2 input.data.

    input.data format (https://compphysvienna.github.io/n2p2/topics/cfg_file.html):
        begin
        comment <comment>
        lattice <ax> <ay> <az>
        lattice <bx> <by> <bz>
        lattice <cx> <cy> <cz>
        atom <x1> <y1> <z1> <e1> <c1> <n1> <fx1> <fy1> <fz1>
        ...
        energy <energy>
        charge <charge>
        end

    Args:
        crys (Crystal): cspy Crystal object to convert.
        **kwargs: Additional keyword arguments to pass to the conversion function.

    Returns:
        str: String representation of the crystal in n2p2 input.data format.
    """
    content = ['begin']
    content.append(
        'comment   ' + kwargs.get('comment', crys.titl)
    )
    for vector in crys.unit_cell.direct:
        content.append(
            "lattice   {:.16e} {:.16e} {:.16e}".format(*vector)
        )
    for elem, pos in zip(crys.asymmetric_unit.elements, crys.site_positions):
        x, y, z = crys.unit_cell.to_cartesian(pos) # n2p2 input.data uses direct coords
        content.append(
            "atom   {:.16e} {:.16e} {:.16e} {} {} {} {:.16e} {:.16e} {:.16e}".format(
                x, y, z, elem, 0.0, 0.0, 0.0, 0.0, 0.0,
            )
        )
    content.append(
        f"energy   {crys.properties.get('energy', 0.0):.16e}"
    )
    content.append(
        f"charge   {crys.properties.get('charge', 0.0):.16e}"
    )
    content.append('end\n')

    return "\n".join(content)


def main():
    import argparse
    import os

    parser = argparse.ArgumentParser()

    parser.add_argument(
        'filepath',
        type=str,
        nargs='+',
        help='file to convert'
    )
    parser.add_argument(
        '-au',
        '--atomic-units',
        action='store_true',
        default=False,
        help='lengths in atomic units rather than angstrom',
    )

    args = parser.parse_args()

    for fpath in args.filepath:
        fmt = fpath.split('.')[-1]
        name = os.path.basename(fpath).split('.')[0]

        if fmt == 'res':
            file_content = Path(fpath).read_text()
            crys = Crystal.from_shelx_string(file_content)
            titl = crys.titl
            crys = crys.as_P1()
            if len(titl.split('_')) == 3:
                content = titl.split('_')
                try:
                    energy = float(content[1])
                    crys.properties['energy'] = energy
                except Exception:
                    print('Unable to read energy from res title')
            to_n2p2_input_data_file(crys, name + '.data')
        elif fmt == 'data':
            for crys in from_n2p2_input_data_file(
                fpath, atomic_units=args.atomic_units
            ):
                crys.save(name + '.res')


if __name__ == "__main__":
    main()
