stages:
  - buildandtest
image: python:3.11

buildandtest:
  stage: buildandtest
  script:
    - apt-get update && apt-get install -y build-essential gfortran libopenmpi-dev libspatialindex-dev python3-dev gcc
    - apt-get clean
    - pip install -e .[all]
    # - python setup.py build_ext --inplace
    - pytest -v
    # - python setup.py bdist_wheel

  artifacts:
    paths:
      - dist/*.whl
    expire_in: 1 day
