[pytest]
python_files = test*.py
markers = 
    binaries: mark a test as requiring external binaries to be installed
    pynnp: mark a test as requiring pynnp to be installed
addopts = --ignore=cspy/deprecated/ --ignore=cspy/conf_search/
log_level = DEBUG
norecursedirs = docs *.egg-info .git .tox
testpaths = cspy
filterwarnings = ignore::DeprecationWarning
