    file_name.write("# Function to check if the VASP-SP calculation is properly running\n")
    file_name.write("scf_checks () {\n")
    file_name.write("TOTEN=$1\n")
    file_name.write("echo \"~    + [$(date +%Y-%m-%d)] $(date +%H:%M:%S) - "\
                    "Checking SCF's dE values within OSZICAR\"\n")
    file_name.write("while [ -z \"$TOTEN\" ];do\n")
    file_name.write("  dE=$(grep 'DAV' OSZICAR | tail --line=1 | awk '{print $4}')\n")
    file_name.write("  dE2F=$(echo \"$(awk \"BEGIN {print $dE}\")\" | awk '{printf \"%.6f\", $0}')\n")
    file_name.write("  echo \"~    + [$(date +%Y-%m-%d)] $(date +%H:%M:%S) - SCF... dE = $dE2F\"\n")
    file_name.write("  if [ $(echo \"$dE2F < 0\" | bc -l) -eq 1 ]; then\n")
    file_name.write("    ENER=$(echo \"$dE2F * -1\" | bc -l)\n")
    file_name.write("    if (( $(echo \"$ENER > 10000000\" | bc -l) ));then\n")
    file_name.write("      echo \"~    + [$(date +%Y-%m-%d)] $(date +%H:%M:%S) - "\
                    "SCF is not converging well! Stopping VASP-SP calculation.\"\n")
    file_name.write("      vasp_sp_process_id=$(squeue --name=\"$JobName\" -h -o %A)\n")
    file_name.write("      scancel $vasp_sp_process_id\n")
    file_name.write("      cp OSZICAR $WD/OSZICAR.failed\n")
    file_name.write("      echo \"${JobName:2}\" >> $WD/../failed_set_for_vasp_sp.dat\n")
    file_name.write("      echo \"~    + [$(date +%Y-%m-%d)] $(date +%H:%M:%S) - Stopping VASOPT.sh as well!\"\n")
    file_name.write("      vasop_process_id=$(queue --name=\"VASOPT\" -h -o %A)\n")
    file_name.write("      scancel $vasopt_process_id\n")
    file_name.write("      exit\n")
    file_name.write("    else\n")
    file_name.write("      TOTEN=$(grep 'free  energy   TOTEN  =' OUTCAR)\n")
    file_name.write("    fi\n")
    file_name.write("  else\n")
    file_name.write("    if (( $(echo \"$dE2F > 10000000\" | bc -l) ));then\n")
    file_name.write("      echo \"~    + [$(date +%Y-%m-%d)] $(date +%H:%M:%S) - "\
                    "SCF is not converging well! Stopping VASP-SP calculation.\"\n")
    file_name.write("      vasp_sp_process_id=$(squeue --name=\"$JobName\" -h -o %A)\n")
    file_name.write("      scancel $vasp_sp_process_id\n")
    file_name.write("      cp OSZICAR $WD/OSZICAR.failed\n")
    file_name.write("      echo \"${JobName:2}\" >> $WD/../failed_set_for_vasp_sp.dat\n")
    file_name.write("      echo \"~    + [$(date +%Y-%m-%d)] $(date +%H:%M:%S) - Stopping VASOPT.sh as well!\"\n")
    file_name.write("      vasop_process_id=$(queue --name=\"VASOPT\" -h -o %A)\n")
    file_name.write("      scancel $vasopt_process_id\n")
    file_name.write("      exit\n")
    file_name.write("    else\n")
    file_name.write("      TOTEN=$(grep 'free  energy   TOTEN  =' OUTCAR)\n")
    file_name.write("    fi\n")
    file_name.write("  fi\n")
    file_name.write("  sleep 2m\n")
    file_name.write("done\n")
    file_name.write("echo \"~    + [$(date +%Y-%m-%d)] $(date +%H:%M:%S) - Check finished. SCF done!\"\n")
    file_name.write("}\n")
