"""cluster_from_crest.py: Clusters crest results using torsional angles."""

#__author__      = "James Bramley"
#__email__   = "J.Bramley@soton.ac.uk"


#REQUIREMENTS!!!
# Obabel and torsional angles for clustering.
# overlay.py script note, the ovelay script will be implimented within this one.

import argparse

#setup arguments for argparse.
parser = argparse.ArgumentParser(description='Cluster conformers from a single CREST search')
parser.add_argument('-xyz','--xyz_file', type=str, metavar='', help='Name of xyz file for clustering.')
parser.add_argument('-t','--torsions', type=str, default=False, metavar='', help='List of torsion angles for the molecule equal to the first conformer of the series.')
parser.add_argument('-np', '--processors', type=int, metavar='', default=1, help='Number of processors used.')
parser.add_argument('-o', '--overlay', action='store_true', help='Perform an overlay on molecules before clustering, recommended if multiplicity not included in the torsion file.')
parser.add_argument('-r', '--reset', action='store_true', help='Deletes directories and files for a hard reset.')

# parser.add_argument('-c', '--cluster', action='store_true', help='Clusters single crest search.')
parser.add_argument('-nc', '--no_cleanup', action='store_true', help='Preserves files and results from individual CREST searches.')

group = parser.add_mutually_exclusive_group()
group.add_argument('-mc', '--multi_cluster', type=int, default=0, help='Clusters multiple crest searches together.')
group.add_argument('-c', '--cluster', action='store_true', help='Clusters single crest search.')
args=parser.parse_args()

import subprocess
#import numpy as np
from multiprocessing import Pool
import shutil
import cspy

from rdkit import Chem
from rdkit.Chem.rdFreeSASA import SASAAlgorithm
from rdkit.Chem import rdFreeSASA
from rdkit.Chem import AllChem

#import sys
import os
#from webbrowser import get
import pandas as pd

#created arguments
ident=args.xyz_file.split('.xyz')[0]
#clustering arguments
single_angle=5
rms_angle=10
_EV_TO_KJMOL = 96.48530749925794

crest_searches=[]
number_searches=args.multi_cluster

for search_number in range(number_searches):
    search_number+=1
    crest_searches.append("crest_"+str(search_number))

print("Running with {} cores.".format(args.processors))

#RESET CURRENTLY NOT WORKING
def reset():
    if os.path.isdir('conformers'):
        shutil.rmtree('conformers')
    #     print('Directory \"conformers\" exists.')
    #     response=input('You are about to delete {}/conformers recurrsively. Type \"CONFIRM\" to continue.'.format(os.getcwd()))
    #     if response == ("CONFIRM"):
    #         shutil.rmtree('conformers')
    #     else:
    #         print("The program needs to delete this directory to run properly. Exiting.")
    #         quit()

    # shutil.rmtree('conformers')

#runs the crest program on molecule.
def crest(molecule, processes):
    bashCommand = "crest {} -T {}".format(molecule, processes)
    process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()

#splits combined xyz files into individual files and places these into the conformers directory
def obabel(molecule_name):
    if not os.path.isdir('conformers'):
        os.mkdir('conformers')
    #add check to see if obabel is installed
    bashCommand = "obabel crest_combined.xyz -O conformers/{}_.xyz -m".format(molecule_name)
    process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    #if error ask user if they would like to install obabel, if yes, install obabel, if no, exit.

#Splits a combined xyz file into multiple mol2 files for torsional angle clustering.
def xyz_to_mol(molecule_name, list_of_conformers):
    bashCommand = "obabel combined.xyz -O {}_.mol2 -m".format(molecule_name)
    process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    os.remove('combined.xyz')


#creates a conformer list for a molecule
def conformer_list(molecule, extension='.xyz'):
    conformers=[]
    number_of_conformers = len([f for f in os.listdir() if f.endswith('.xyz') and f.startswith(str(molecule)) and os.path.isfile(os.path.join(f))])
    for conformer_number in range(1, number_of_conformers+1):
        conformers.append(str(molecule)+"_"+str(conformer_number) + str(extension))
    return conformers

#combines the a list of files.
def combine_files(list_of_filenames, combined_name):
    with open(str(combined_name), 'w') as outfile:
        for fname in list_of_filenames:
            with open(fname) as infile:
                outfile.write("{}\n".format(infile.read()))

#get the energy of the conformer generated by CREST (second line of xyz)
def get_energy(conformer):
    with open(conformer) as fp:
        for i, line in enumerate(fp):
            if i == 1:
                energy=line.split()[0]
    return energy

#get the area of the conformer generated by CREST, multiprocessing should be used here
def get_area(list_of_conformers, processors):
    def single_core_area(list_of_conformers):
    #need to convert to mol file, can this be done in cspy?
        for conformer in list_of_conformers:
            m1 = Chem.MolFromMolFile(list_of_conformers)
            hmol1 = Chem.AddHs(m1)
            ptable = Chem.GetPeriodicTable()
            radii1 = [ptable.GetRvdw(atom.GetAtomicNum()) for atom in hmol1.GetAtoms()]
            
            #surface area calculation options
            opts = rdFreeSASA.SASAOpts()
            opts.algorithm = SASAAlgorithm.ShrakeRupley
            opts.probeRadius = 1.8

            area = rdFreeSASA.CalcSASA(hmol1, radii1, opts=opts)
            return area

    chunks = [list_of_conformers[i::processors] for i in range(processors)]
    pool = Pool(processes=processors)
    result = pool.map(get_area, chunks)

# def create_table(list_of_conformers, headers=[energy=False, area=False):
#     if os.path.isfile('table.txt'):
#         os.remove('table.txt')
#     for header in headers[1:]:
#         if header=='energy':

#Creates an energy area table for conformer analysis
def create_eng_area_table(list_of_conformers, processors):
    if os.path.isfile('eng_area.txt'):
        os.remove('eng_area.txt')

    def single_core_create(list_of_conformers, processors):
        for conformer in conformer_list(ident):
            with open('eng_area.txt', 'a') as ea:
                ea.write("{} {} {}\n".format(conformer, get_energy(conformer), get_area(conformer)))

    chunks = [list_of_conformers[i::processors] for i in range(processors)]
    pool = Pool(processes=processors)
    result = pool.map(single_core_create, chunks)

    df = pd.read_csv('eng_area.txt', delimiter=' ', header=None)
    df.columns=['conformer','energy', 'area']
    df = df.sort_values(by='energy')
    
#relabels all conformers so they exist in energtic order
def sort(list_of_conformers):
    df = pd.read_csv('energies.txt', sep=' ', header=None)
    df.columns=['conformer','energy']
    df = df.sort_values(by=['energy'])
    ordered_confs = df['conformer']
    
    if not os.path.isdir('reordered'):
        os.mkdir('reordered')
    
    counter=0

    for conformer in ordered_confs:
        counter+=1
        os.rename(str(conformer), "reordered/"+str(ident)+'_'+str(counter) + '.xyz')
    

    for conformer in list_of_conformers:
        os.rename("reordered/"+str(conformer), str(conformer))

    if os.path.isfile('energies.txt'):
        os.remove('energies.txt')
    for conformer in list_of_conformers:
        with open('energies.txt', 'a') as en:
            en.write("{} {}\n".format(conformer, get_energy(conformer)))
          
    os.rmdir("reordered")

#Old overlay script - CURRENTLY NOT WORKING FOR PARALLELISATION
#START
#overlays all xyz files in list with the first member of the list. Resorting all atoms in place.
# def overlay(list_of_conformers, processors):
#     if not os.path.isdir('overlayed'):
#         os.mkdir('overlayed')

#     master = list_of_conformers[0]
#     print("The master conformer is {}".format(master))
#     to_compare = list_of_conformers[1:]
#     m1 = cspy.Molecule.load(master)
#     m1.save("overlayed/"+str(master))



#     def single_core_overlay(file_list):
#         for file in file_list:
#             m2 = cspy.Molecule.load(file)
#             m3, order, rmsd = m1.overlay(m2)
#             print("{} overlay complete, saving to overlayed".format(file))
#             m3.save("overlayed/"+str(file))

#     # single_core_overlay(list_of_conformers)

#     def multi_core_overlay(file_list):
#         chunks = [file_list[i::processors] for i in range(processors)]
#         pool = Pool(processes=processors)
#         result = pool.map(single_core_overlay, chunks)

#     multi_core_overlay(to_compare)

#     for conformer in list_of_conformers:
#         os.rename("overlayed/"+str(conformer), str(conformer))
    
#     os.rmdir("overlayed")

#END

#Overlays molecules to ensure atom ordering is correct. Uses the first item in "list_of_conformers" as reference conformation.
def overlay(list_of_conformers, processors):
    print("Overlaying xyz files...")
    bashCommand = "python -m cspy.conf_search.overlay {} {} {}".format(ident, len(list_of_conformers), processors)
    process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    print("Overlay complete")

def overlay_to_original(energies_file, processors):
    print("Overlaying xyz files...")
    bashCommand = "python -m cspy.conf_search.overlay_v2 -e {} -m original.xyz -np {}".format(energies_file, processors)
    process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    print("Overlay complete")

#clusters xyz files by their torsional angles
#can we use cspy to convert to .mol2?
# def cluster(molecule, list_of_conformers, rms_max, single_max, processors):
#     shutil.copyfile('../'+args.torsions, str(ident)+'_torsions')
#     nconfs = len(list_of_conformers)
#     print('Clustering {} conformers...'.format(nconfs))
#     bashCommand = "python /home/jb24g16/cspy-git/cspy/conf_search/torsions.py {}_ {} no {} {}".format(molecule, nconfs, rms_max, single_max)
#     process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
#     output, error = process.communicate()
#     for mol in conformer_list(molecule, extension='.mol2'):
#         os.remove(mol)
#     print("Clustering complete.")

def cluster(molecule, list_of_conformers, rms_max, single_max, processors):
    shutil.copyfile('../'+args.torsions, str(ident)+'_torsions')
    torsions_file=str(ident)+'_torsions'
    nconfs = len(list_of_conformers)
    print('Clustering {} conformers...'.format(nconfs))
 #   bashCommand = "python -m cspy.conf_search.dihedral -e energies.txt -np {} -t {}".format(args.processors, torsions_file)
    bashCommand = "python -m cspy.conf_search.rmsd -e energies.txt -np {}".format(args.processors)
    process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    # for mol in conformer_list(molecule, extension='.mol2'):
    #     os.remove(mol)
    print("Clustering complete.")

#creates uniques.txt file which stores the conformer numbers of unique conformations from the clustering
def get_uniques():
    uniques_list=[]
    with open('clusters_careful_'+ str(single_angle) + '_' + str(rms_angle) + '.txt', 'r') as clusters:
        for line in clusters:
            uniques_list.append(line.split()[0])
    uniques_list_fn=[str(ident)+'_'+str(n)+'.xyz' for n in uniques_list]
    combine_files(uniques_list_fn, 'uniques.xyz')
    with open('uniques.txt', 'a') as uniques:
        for unique in uniques_list:
            uniques.write("{}\n".format(unique))
    print("{} total unique conformers found.".format(len(uniques_list)))

def cleanup():
    combine_files(conformer_list(ident)[:-1], 'generated_structures.xyz')
    for xyz in conformer_list(ident)[:-2]:
        os.remove(xyz)
    

#############################################################################################################################
#MAIN FUNCTION
def cluster_single_search(ident, processors):
    if args.reset:
        reset()
    combine_files(["crest_conformers.xyz"], 'crest_combined.xyz') #removed rotamers that were unnecessary duplicates - future versions of code should remove this file combination all together
    obabel(ident)
    os.chdir('conformers')
    if os.path.isfile('../original.xyz'):
        shutil.copyfile("../original.xyz", "original.xyz")
    elif os.path.isfile('../'+args.xyz_file):
        shutil.copyfile('../'+args.xyz_file, "original.xyz")
    if os.path.isfile('energies.txt'):
        os.remove('energies.txt')
    for conformer in conformer_list(ident):
        with open('energies.txt', 'a') as en:
            en.write("{} {}\n".format(conformer, get_energy(conformer)))
    sort(conformer_list(ident))
    if args.overlay:
        # overlay(conformer_list(ident), processors)
        overlay_to_original("energies.txt", processors)
    
    combine_files(conformer_list(ident), 'combined.xyz')
    # xyz_to_mol(ident, conformer_list(ident))

    cluster(ident, conformer_list(ident), single_angle, rms_angle, args.processors)
    # get_uniques()
    # cleanup()


#Combines multiple CREST searches together and clusters between them. Should be ran from directory above all positions.
def cluster_searches(ident, processors):
    if args.reset:
        reset()
    if not os.path.isdir('conformers'):
        os.mkdir('conformers')
    total_conformer_count=0
    directory=os.getcwd()
    for search in crest_searches: #position_1, position_2, ..
        os.chdir(str(search))
        shutil.copyfile('../'+args.torsions, args.torsions)
        shutil.copyfile('../'+args.xyz_file, "original.xyz")
        cluster_single_search(ident, processors)
        print("Collecting conformers from {}".format(search))
        with open("uniques.txt", 'r') as uniques: #for every unique conformer
            for conformer in uniques: #was line
                conformer=str(conformer).strip()
                total_conformer_count+=1
                # conformer=str(ident) + '_' + str(line).strip() + '.xyz'
                new_conformer_name=str(ident) + '_' + str(total_conformer_count) + '.xyz'
                with open(str(directory)+'/conformers/energies.txt', 'a') as energies:
                    energies.write('{} {}\n'.format(new_conformer_name, get_energy(conformer)))
                shutil.copyfile(conformer, str(directory)+'/conformers/'+str(new_conformer_name))
        os.chdir('..')
        shutil.rmtree('conformers')
        os.chdir(directory)
    os.chdir('conformers')
    shutil.copyfile('../'+args.xyz_file, "original.xyz")
    sort(conformer_list(ident))
    if args.overlay:
        # overlay(conformer_list(ident), processors)
        overlay_to_original("energies.txt", processors)
    
    combine_files(conformer_list(ident), 'combined.xyz')
    # xyz_to_mol(ident, conformer_list(ident))

    cluster(ident, conformer_list(ident), single_angle, rms_angle, args.processors)

    os.chdir("..")
    if not args.no_cleanup:
        for search in crest_searches:
            shutil.rmtree(str(search))

    # get_uniques()
    # cleanup()

# def total_cluster():
#     for search in searches:
#         os.chdir()
#     cluster_single_search(ident, args.processors)
#     #change to working directory
#     cluster_searches(ident, args.processors)

if __name__ == '__main__':
    if args.cluster:
        cluster_single_search(ident, args.processors)
    if args.multi_cluster > 0:
        cluster_searches(ident, args.processors)
