from cspy.db import CspDataStoreAUs
from cspy.crystal.generate_crystal import CrystalGenerator
from cspy.chem.molecule import Molecule
from cspy.util.misc import mp_check_reservation
import multiprocessing
import argparse
import math
import random
import numpy as np
import json
import time
from cspy.chem.energy import boltzmann_weighting
import logging
from typing import Tuple, Union, Optional

LOG = logging.getLogger(__name__)

def select_AU(aus : list, properties : dict, weights : list, seed : int) -> Molecule:
    """Randomly (not Quasi) selects an asymmetric unit from a dictionary.
    Random choice is weighted.

        Parameters
        ----------
        aus : list
            List of asymmetric units where each asymmetric unit is represented by a string id

        properties : dict
            Dict of asymmetric unit properties (must include key 'xyz_coordinates')
            where keys are the same as the string ids from aus

        weights : list
            List of floats of same dimensions as aus.
            Each float represent the chance of picking the corresponding asymmetric unit
            from aus.

        seed : int
            Random seed

        Returns
        -------
        cspyMol : Molecule obj
            Molecule object where the whole asymmetric unit is treated as a single molecule
        """
    random.seed(seed)
    au = random.choices(aus, weights = weights, k = 1)[0]

    xyz_string = properties[au]['xyz_coordinates']
    cspyMol = Molecule.from_xyz_string(xyz_string)

    return cspyMol


def generate_crystal(aus : list, properties : dict, sg : int, weights : list , Q : int, workers : int, num_crystals : int):
    """Generate crystals using the asymmetric unit transplate algorithm.
    Crystals are written as .res files.

        Parameters
        ----------
        aus : list
            List of asymmetric units where each asymmetric unit is represented by a string id

        properties : dict
            Dict of asymmetric unit properties (must include key 'xyz_coordinates')
            where keys are the same as the string ids from aus

        weights : list
            List of floats of same dimensions as aus.
            Each float represent the chance of picking the corresponding asymmetric unit
            from aus.

        sg : int
            Spacegroup of crystals to be generated

        Q : int
            Unique worker id for parallel process. Used for mp_check_reservation function

        workers : int
            Number of workers operating in parallel. Used for mp_check_reservation function

        num_crystals : int
            Number of crystals to be generated

        Returns
        -------
        generated : .res file
            Molecular crystal generated by the CSPy CrystalGenerator class 
            while treating an entire asymmetric unit as a single molecule.
        """
    
    num_valid = 0
    seed = 1
    while True:
        if mp_check_reservation(seed, Q, workers):
            crystals = []
            cspyMol = select_AU(aus, properties, weights, seed)
            if cspyMol:
                num_cells = 1
                for cell_index in range(num_cells):
                    mutator = seed * cell_index
                    clg = CrystalGenerator([cspyMol], sg, tvp=2.5, nudge=3,  adaptcell=True, asi=False)
                    generated = clg.generate(seed+mutator, overrides={'translations' : None, 'rotations': None})

                    if generated:
                        crystals.append(generated)

            num_valid += len(crystals)

            for ind, generated in enumerate(crystals):
                generated.to_shelx_file(str(seed) + '_' + str(ind) + '.res')

            if num_valid == num_crystals or num_valid > num_crystals:
                break
        seed += 1
    

def main(sys_args=None):
        parser = argparse.ArgumentParser(
                prog='cspy-sauce clg_aut',
                description='Read all asymmetric units from database and generate candidate crystals')
        parser.add_argument('database', type=str,
                help='Specify database file to read')
        parser.add_argument("-x", "--xyz-files", nargs="+", type=str,
                help="Xyz files containing molecules for generation")
        parser.add_argument('-sg', '--spacegroup', type=int,
                help='Specify spacegroup of crystal to generate')
        parser.add_argument('-np', '--numproc', type=int,
                help='Specify number of paralllel process')
        parser.add_argument('-nc', '--numcrys', type=int,
                help='Specify number of crystals to sample')
        parser.add_argument(
                "--log-level", type=str,
                choices=("INFO", "DEBUG", "ERROR", "WARN"),
                default="INFO",
                help="Control level of logging output")
        
        args = parser.parse_args(sys_args)

        logging.basicConfig(
        level=args.log_level,
        format='%(asctime)s - %(levelname)s - %(module)s %(lineno)d - '
               '%(message)s')

        workers = args.numproc
        num_crystals = args.numcrys
        sg = args.spacegroup

        crys_per_worker = math.floor(num_crystals / workers)
        num_crys_distribution = [crys_per_worker for _ in range(workers)]
        for ind, _ in enumerate(range(num_crystals - (crys_per_worker * workers))):
            num_crys_distribution[ind] += 1

        db_name = args.database
        LOG.info("Reading database")
        db = CspDataStoreAUs(db_name)
        LOG.info("Done reading database")

        manager = multiprocessing.Manager()
        properties = manager.dict()
        for row in db.select("asym_units",
                                ['id','energy',
                                'xyz_coordinates','molecule_ids']):
            properties[row[0]]={"energy" : row[1], "xyz_coordinates" : row[2], "molecule_ids" : row[3]}

        molecules = dict()
        for row in db.select("molecules", ['id','xyz_coordinates', 'equivalent_atoms']):
            molecules[row[0]] = [int(row[1].split('\n')[0]), json.loads(row[2])]

        aus = list(properties.keys())
        energies = []

        for au in aus:
            energy = properties[au]['energy']
            energies.append(energy)
        
        energies = np.asarray(energies)
        weights = boltzmann_weighting(energies)

        start = time.time()

        with multiprocessing.Pool(workers) as pool:
            pool.starmap(generate_crystal, [[aus, properties, sg, weights, Q, workers, num_crys_distribution[Q]] for Q in range(workers)])
            
        LOG.info("Runtime: %d" , time.time() - start)